In [1]:
import pandas as pd
import pickle
from sklearn.model_selection import KFold

In [2]:
train = pd.read_csv("../../data/sequential_train.csv", nrows=10000)
# test = pd.read_csv("../../data/test_feature_engineering.csv")

In [6]:
user_id = train['userID'].unique()

In [4]:
kf = KFold(5, shuffle=True, random_state=42)
tmp = kf.split(train['userID'].unique())
next(iter(tmp))

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 12, 13]), array([ 0,  9, 11]))

In [8]:
user_id[[1,2,3,4,5,6,7,8,10,12,13]]

array([ 1,  2,  5,  6,  7,  8,  9, 10, 12, 15, 16])

In [5]:
with open("./asset/cate2id_dict.pickle",'rb') as fr:
    cate2id_dict = pickle.load(fr)  

In [7]:
cate2id_dict['assessmentItemID']

{0: 1,
 1: 2,
 2: 3,
 3: 4,
 4: 5,
 5: 6,
 6: 7,
 7: 8,
 8: 9,
 9: 10,
 10: 11,
 11: 12,
 12: 13,
 13: 14,
 14: 15,
 15: 16,
 16: 17,
 17: 18,
 18: 19,
 19: 20,
 20: 21,
 21: 22,
 22: 23,
 23: 24,
 24: 25,
 25: 26,
 26: 27,
 27: 28,
 28: 29,
 29: 30,
 30: 31,
 31: 32,
 32: 33,
 33: 34,
 34: 35,
 35: 36,
 36: 37,
 37: 38,
 38: 39,
 39: 40,
 40: 41,
 41: 42,
 42: 43,
 43: 44,
 44: 45,
 45: 46,
 46: 47,
 47: 48,
 48: 49,
 49: 50,
 50: 51,
 51: 52,
 52: 53,
 53: 54,
 54: 55,
 55: 56,
 56: 57,
 57: 58,
 58: 59,
 59: 60,
 60: 61,
 61: 62,
 62: 63,
 63: 64,
 64: 65,
 65: 66,
 66: 67,
 67: 68,
 68: 69,
 69: 70,
 70: 71,
 71: 72,
 72: 73,
 73: 74,
 74: 75,
 75: 76,
 76: 77,
 77: 78,
 78: 79,
 79: 80,
 80: 81,
 81: 82,
 82: 83,
 83: 84,
 84: 85,
 85: 86,
 86: 87,
 87: 88,
 88: 89,
 89: 90,
 90: 91,
 91: 92,
 92: 93,
 93: 94,
 94: 95,
 95: 96,
 96: 97,
 97: 98,
 98: 99,
 99: 100,
 100: 101,
 101: 102,
 102: 103,
 103: 104,
 104: 105,
 105: 106,
 106: 107,
 107: 108,
 108: 109,
 109: 110,
 110: 11

In [10]:
sum([0.8305820163094465, 0.8225809365515248, 0.8159330915828863, 0.8280639842642677])/4

0.8242900071770313

In [3]:
train.columns

Index(['userID', 'assessmentItemID', 'testId', 'answerCode', 'Timestamp',
       'KnowledgeTag', 'assessmentItemID_last', 'testId_first', 'testId_last',
       'elapsed', 'accuracy_by_assessment', 'accuracy_by_test',
       'accuracy_by_tag', 'accuracy_by_assessment_last',
       'accuracy_by_test_first', 'accuracy_by_test_last',
       'relative_answered_correctly', 'prior_ac_count', 'prior_quest_count',
       'prior_ac_accuracy', 'prior_relative_ac_sum', 'prior_relative_accuracy',
       'prior_assessment_frequency', 'prior_test_frequency',
       'prior_tags_frequency', 'diff_time_btw_tags', 'prev_tag_answer',
       'trend_elapsed', 'seasonal_elapsed', 'resid_elapsed',
       'trend_accuracy_by_assessment', 'seasonal_accuracy_by_assessment',
       'resid_accuracy_by_assessment', 'trend_accuracy_by_test',
       'seasonal_accuracy_by_test', 'resid_accuracy_by_test',
       'trend_accuracy_by_tag', 'seasonal_accuracy_by_tag',
       'resid_accuracy_by_tag', 'trend_accuracy_by_asses

In [82]:
tmp = pd.read_csv("../../data/total.csv")

In [86]:
tmp[tmp['answerCode']!=-1].to_csv("../../data/total_except.csv", index=False)

In [4]:
cate_cols = [
    'KnowledgeTag', 'assessmentItemID_last', 'testId_first', 'testId_last'
]
cont_cols=[
    'elapsed', 'accuracy_by_assessment', 'accuracy_by_test',
    'accuracy_by_tag', 'accuracy_by_assessment_last',
    'accuracy_by_test_first', 'accuracy_by_test_last',
    'trend_prior_ac_count',
    'seasonal_prior_ac_count', 'resid_prior_ac_count',
    'trend_prior_quest_count', 'seasonal_prior_quest_count',
    'resid_prior_quest_count', 'trend_prior_ac_accuracy',
    'seasonal_prior_ac_accuracy', 'resid_prior_ac_accuracy',
    'trend_prior_relative_ac_sum', 'seasonal_prior_relative_ac_sum',
    'resid_prior_relative_ac_sum', 'trend_prior_relative_accuracy',
    'seasonal_prior_relative_accuracy', 'resid_prior_relative_accuracy',
    'trend_prior_assessment_frequency',
    'seasonal_prior_assessment_frequency',
    'resid_prior_assessment_frequency', 'trend_prior_test_frequency',
    'seasonal_prior_test_frequency', 'resid_prior_test_frequency',
    'trend_prior_tags_frequency', 'seasonal_prior_tags_frequency',
    'resid_prior_tags_frequency', 'trend_diff_time_btw_tags',
    'seasonal_diff_time_btw_tags', 'resid_diff_time_btw_tags',
    'trend_prev_tag_answer', 'seasonal_prev_tag_answer',
    'resid_prev_tag_answer'
]

In [77]:
train.head()

userID assessmentItemID      testId  answerCode            Timestamp  \
0       0       A060001001  A060000001           1  2020-03-24 00:17:11   
1       0       A060001002  A060000001           1  2020-03-24 00:17:14   
2       0       A060001003  A060000001           1  2020-03-24 00:17:22   
3       0       A060001004  A060000001           1  2020-03-24 00:17:29   
4       0       A060001005  A060000001           1  2020-03-24 00:17:36   

   KnowledgeTag  assessmentItemID_last  testId_first  testId_last   elapsed  \
0          7224                      1             6            1  0.000000   
1          7225                      2             6            1  1.386294   
2          7225                      3             6            1  2.197225   
3          7225                      4             6            1  2.079442   
4          7225                      5             6            1  2.079442   

   ...  prior_ac_count  prior_quest_count  prior_ac_accuracy  \
0  ...        0.000000           0.000000                0.0   
1  ...        0.693147           0.693147                1.0   
2  ...        1.098612           1.098612                1.0   
3  ...        1.386294           1.386294                1.0   
4  ...        1.609438           1.609438                1.0   

   prior_relative_ac_sum  prior_relative_accuracy  prior_assessment_frequency  \
0                  0.000                    0.000                         0.0   
1                  0.016                    0.016                         0.0   
2                  0.048                    0.024                         0.0   
3                  0.132                    0.044                         0.0   
4                  0.160                    0.040                         0.0   

   prior_test_frequency  prior_tags_frequency  diff_time_btw_tags  \
0              0.000000              0.000000           17.086642   
1              0.693147              0.000000           17.086642   
2              1.098612              0.693147            2.197225   
3              1.386294              1.098612            2.079442   
4              1.609438              1.386294            2.079442   

   prev_tag_answer  
0              0.0  
1              0.0  
2              1.0  
3              1.0  
4              1.0  

[5 rows x 27 columns]

In [78]:
test.head()

userID assessmentItemID      testId  answerCode            Timestamp  \
0       3       A050023001  A050000023           1  2020-01-09 10:56:31   
1       3       A050023002  A050000023           1  2020-01-09 10:56:57   
2       3       A050023003  A050000023           0  2020-01-09 10:58:31   
3       3       A050023004  A050000023           0  2020-01-09 10:58:36   
4       3       A050023006  A050000023           0  2020-01-09 10:58:43   

   KnowledgeTag  assessmentItemID_last  testId_first  testId_last   elapsed  \
0          2626                      1             5           23  0.000000   
1          2626                      2             5           23  3.295837   
2          2625                      3             5           23  4.553877   
3          2625                      4             5           23  1.791759   
4          2623                      6             5           23  2.079442   

   ...  prior_ac_count  prior_quest_count  prior_ac_accuracy  \
0  ...        0.000000           0.000000           0.000000   
1  ...        0.693147           0.693147           1.000000   
2  ...        1.098612           1.098612           1.000000   
3  ...        1.098612           1.386294           0.666667   
4  ...        1.098612           1.609438           0.500000   

   prior_relative_ac_sum  prior_relative_accuracy  prior_assessment_frequency  \
0                  0.000                 0.000000                         0.0   
1                  0.340                 0.340000                         0.0   
2                  0.720                 0.360000                         0.0   
3                  0.172                 0.057333                         0.0   
4                 -0.464                -0.116000                         0.0   

   prior_test_frequency  prior_tags_frequency  diff_time_btw_tags  \
0              0.000000              0.000000           17.086642   
1              0.693147              0.693147            3.295837   
2              1.098612              0.000000           17.086642   
3              1.386294              0.693147            1.791759   
4              1.609438              0.000000           17.086642   

   prev_tag_answer  
0              0.0  
1              1.0  
2              0.0  
3              0.0  
4              0.0  

[5 rows x 27 columns]

In [60]:
offset = 1
with open('./asset/cate2id_dict.pickle','rb') as fr:
    cate2id_dict = pickle.load(fr)  
for col in cate_cols:    
    test[col] = test[col].map(cate2id_dict[col])
    offset += len(cate2id_dict[col])

In [75]:
test.head()

In [69]:
import torch
def get_row_ids_test(df, max_seq_len):
    import pdb; pdb.set_trace()
    # 데이터 증강을 위한 row_id 저장 -> dataset 생성시 활용
    df = df.reset_index().rename({'index':'row_id'}, axis=1)
    # 학습 과정에서 학습 샘플을 생성하기 위해서 필요한 유저별 row_ids를 저장
    question_row_ids_by_user_id = df.groupby('userID').apply(lambda x: x['row_id'].values)
    user_id_row_id_start_end = []
    for user_id, row_ids in question_row_ids_by_user_id.items():
        target_row_ids = row_ids[-max_seq_len:]
        user_id_row_id_start_end.append([user_id, target_row_ids[0], target_row_ids[-1]+1])

    return user_id_row_id_start_end


class DKTDataset_test(torch.utils.data.Dataset):
    def __init__(self, data, max_seq_len=20, cate_cols=cate_cols, cont_cols=cont_cols):

        self.max_seq_len = max_seq_len
        
        self.user_id_row_id_list = get_row_ids_test(data, self.max_seq_len)

        self.cate_cols = cate_cols
        self.cont_cols = cont_cols
        
        self.cate_features = data[self.cate_cols].values
        self.cont_features = data[self.cont_cols].values
        self.target = data['answerCode'].values

    def __getitem__(self, index):
        user_id, start_row_id, end_row_id = self.user_id_row_id_list[index]
        seq_len = end_row_id - start_row_id

        # 0으로 채워진 output tensor 제작
        cate_feature = torch.zeros(self.max_seq_len, len(self.cate_cols), dtype=torch.long)
        cont_feature = torch.zeros(self.max_seq_len, len(self.cont_cols), dtype=torch.float)
        target = torch.zeros(self.max_seq_len, dtype=torch.float)
        mask = torch.zeros(self.max_seq_len, dtype=torch.int16)
        
        # tensor에 값 채워넣기
        cate_feature[-seq_len:] = torch.ShortTensor(self.cate_features[start_row_id:end_row_id])
        cont_feature[-seq_len:] = torch.HalfTensor(self.cont_features[start_row_id:end_row_id])
        target[-seq_len:] = torch.HalfTensor(self.target[start_row_id:end_row_id])
        mask[-seq_len:] = 1     
        
        return cate_feature, cont_feature, mask, target

    def __len__(self):
        return len(self.user_id_row_id_list)

def get_loaders_test(test):

    pin_memory = False
    test_loader = None

    testset = DKTDataset_test(test)
    test_loader = torch.utils.data.DataLoader(
        testset,
        num_workers=1,
        shuffle=True,
        batch_size=64,
        drop_last=False,
        pin_memory=pin_memory,
    )
    

    return test_loader

In [63]:
test_ds = DKTDataset_test(test)

In [64]:
test.shape

(260114, 28)

In [65]:
test_ds[0]

TypeError: only integer scalar arrays can be converted to a scalar index

In [70]:
get_row_ids_test(test, 20)

> /tmp/ipykernel_67080/4251677490.py(5)get_row_ids_test()
      3     import pdb; pdb.set_trace()
      4     # 데이터 증강을 위한 row_id 저장 -> dataset 생성시 활용
----> 5     df = df.reset_index().rename({'index':'row_id'}, axis=1)
      6     # 학습 과정에서 학습 샘플을 생성하기 위해서 필요한 유저별 row_ids를 저장
      7     question_row_ids_by_user_id = df.groupby('userID').apply(lambda x: x['row_id'].values)

   row_id  userID  assessmentItemID  testId  answerCode            Timestamp  \
0       0       3              3457   10018           1  2020-01-09 10:56:31   
1       1       3              3458   10018           1  2020-01-09 10:56:57   
2       2       3              3459   10018           0  2020-01-09 10:58:31   
3       3       3              3460   10018           0  2020-01-09 10:58:36   
4       4       3              3462   10018           0  2020-01-09 10:58:43   

   KnowledgeTag  assessmentItemID_last  testId_first  testId_last  ...  \
0         11494                  11904         11923        12026  

In [ ]:
import numpy as np
a = np.arange(40)
a[:18:-1]

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23,
       22, 21, 20, 19])

In [79]:
from args import parse_args

In [80]:
args = parse_args()

usage: ipykernel_launcher.py [-h] [--seed SEED] [--device DEVICE]
                             [--data_dir DATA_DIR] [--asset_dir ASSET_DIR]
                             [--file_name FILE_NAME] [--model_dir MODEL_DIR]
                             [--model_name MODEL_NAME]
                             [--output_dir OUTPUT_DIR]
                             [--output_file_name OUTPUT_FILE_NAME]
                             [--test_file_name TEST_FILE_NAME]
                             [--cate_cols CATE_COLS] [--cont_cols CONT_COLS]
                             [--max_seq_len MAX_SEQ_LEN] [--stride STRIDE]
                             [--num_workers NUM_WORKERS]
                             [--embed_dim EMBED_DIM] [--hidden_dim HIDDEN_DIM]
                             [--n_layers N_LAYERS] [--n_heads N_HEADS]
                             [--drop_out DROP_OUT] [--n_epochs N_EPOCHS]
                             [--batch_size BATCH_SIZE] [--lr LR]
                             [--clip_grad CLI

SystemExit: 2

/opt/conda/envs/dkt/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [81]:
args

NameError: name 'args' is not defined

In [2]:
import numpy as np
np.array([0.8418934825519276, 0.8305820163094465, 0.8225809365515248, 0.8159330915828863, 0.8280639842642677]).mean()

0.8278107022520107

In [3]:
1/3*0.25+1/3*0.5+0.25*1/3


0.3333333333333333

In [4]:
1/3*0.25+1/3*0.25


0.16666666666666666

In [5]:
1/3*0.25


0.08333333333333333

In [6]:
1/3*0.25+1/3*0.2+0.25*1/3


0.23333333333333334

In [7]:
1/3*0.3+0.25*1/3

0.18333333333333332